### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by aggsol** [Seng3694/TexturePacker#1]
Hey, great to see you also had fun re-inventing the wheel :wheel_of_dharma: :wink: 

I am working on an load and render example but I am unsure how to handle rotated sprites. Next to the texture and its rect I need to apply the rotation every time on the vertices. How do you handle that case with SFML? I think about not using rotated sprites at all and live with the overhead. It just makes the code less complex.

Do you mind sharing the 500 test images you used in the example in another repo so we can compare notes? The algorithm you chose packs nicel.y

P.S. I will *steal* some ideas from you like the regex file selection. I hope you don't mind :-)

**Comment by Seng3694** [comment]
Hey, I saw that on your profile and thought for the sake of practice i'll do it on my own 😉 

Actually I did not even try to load and render them.  I guess someone has to write some code to rotate them back 😅 

How it currently works in the packer:
![rotation][1]

First it rotates the texture 90°. Then it resets the origin (origin.y + image.width), so the texture is positioned right. If you wanted to load that texture you had to reverse these steps. Move the origin (origin.y + image.height) and rotate by -90°. Then you should have the source texture. That could end in kind of a mess... well the rotation is optional and disabled for a reason right? 😅 

Sadly I already deleted those test images, but [here][2] is the code I used to generate them. I did not use a custom seed to generate them... so I cannot reconstruct them. I guess I will just upload some reference images with the resulting atlas image so someone can compare directly without first building the project :-)

P.S. You can do whatever you want with this code. If you earn millions because you used some of the code, just write me a nice e-mail or something 😉 

[1]: https://cdn.discordapp.com/attachments/425728769236664350/428547432335409153/rotation.gif
[2]: https://pastebin.com/5Cc7P8Kr

**Comment by Seng3694** [comment]
I added 500 random generated images to the repository with the resulting atlasses (w/o rotation). You can find them [here][1] :-)

Edit: As you can see the result of rotating the textures is really small. There may be cases where rotating the textures will yield better results.

[1]: https://github.com/Seng3694/TexturePacker/tree/master/reference

**Comment by aggsol** [comment]
Ah great! I will have a look. The rotation in pretty much the same way I do it. I just wondered if there is a neat trick to it. I will maybe just do a simple loader then as an example later. Did you do that animted GIF with a specific tool or did just draw every frame? I like the pixelated arrows. :+1:

**Comment by Seng3694** [comment]
I used [Aseprite][1]. You can either buy it on steam or build it from [source][2]. There are also pre-built versions around the internet.

[1]: https://www.aseprite.org/
[2]: https://github.com/aseprite/aseprite

**Comment by Seng3694** [comment]
[Example][1] added  :-)

[1]: https://github.com/Seng3694/TexturePacker/tree/master/example
